{% set name = "libidn" %}
{% set soversion = "11" %}
{% set version = "None" %}
{% set sha256 = "fad8fc14f61e54d8c301719d647d8c605b608b73e7f2df52f48ac945dde82176" %}
{% set am_version = "1.15" %} # keep synchronized with build.sh

package:
  name: {{ name|lower }}{{ soversion }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://ftp.gnu.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0


requirements:
  build:
    - m2-autoconf                  # [win]
    - m2-automake{{ am_version }}  # [win]
    - m2-libtool                   # [win]
    - m2w64-toolchain              # [win]
    - posix                        # [win]
    # for activating features so we link with correct libiconv
    - {{ compiler('c') }}
    - make  # [unix]
  host:
    - libiconv  # [not linux]

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME   # [osx]

about:
  home: https://www.gnu.org/software/libidn/
  license: LGPLv3
  license_family: GPL
  license_file: COPYING.LESSERv3
  summary: "Library for internationalized domain name support"
  description: |
    Libidn is a package for internationalized string handling based on the
    Stringprep, Punycode, IDNA and TLD specifications.  Libidn is a GNU
    project.  See the file COPYING for licensing information.
  doc_url: https://www.gnu.org/software/libidn/#documentation
  dev_url: https://savannah.gnu.org/projects/libidn

extra:
  recipe-maintainers:
    - epruesse
