travis:
  secure:
    BINSTAR_TOKEN: vh6HX9JufIMDz6KdL4mwBpDu4g75ujyTVF2PX6dcf/7yejzKqiCJeGw93Wd/zrKF5AUBbt+K2IxltgqjKUqJgbNEKTv4gkCuzEHV3wEQ8hn/dWvwLB4h928kl8nLgumAsP/q7KEm0I4VJVnudkOVVy61auRwwKX4Jz8UEN1soMk9k6/OH4CjA3gtLv2+GzwC7ryuAJmIU+kzO/nVMlj2OaSYh3XrBeokrKR18JuuWmgTIn7RbnAjxeDtHej81BzfMLD9k67VrLBlbBSMkGhE/Is6hLY11X/pv0kB3Vapz3fD8A9Hq0WPMBRJg1IS1gfR71MgSw4eefTXVrr1y2LTtsetXTLRwyQGmCc/khhcE7c4VwqB72ARMAtoN5ZhOH4ZYPdstfHznAMhc1W3hgHPC4TZqM6ivF7SQrX4mzcKbyD5Eu6megEg7bqBfx38tr+w7wQWqf4/Po6k+rMuvJ75SWCIKI71LKtNqtdYnTTcazejl+MYZvUQnZu3yxuvfu+HLwUEFiX09Op9JnvpOZn1sG2T2S4vMCj7Of1eC0Ow138GzIkrrGO16VMp2lPXXN9UTIbgw7IXlb9gJG3HV7IBn3uH3W76gFJ7xdB7pW1vcnSCbFnq6IsPdfXPy3vkGDnUhWRFwuo8dlxJ6Yvu7dJoDmygKvKbHTlAd4dxkeIQp9A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
